# Generated by Django 3.2 on 2023-12-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fec_devolucion',
            new_name='fecha_devolucion',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fec_prestamo',
            new_name='fecha_prestamo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_pags',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
